/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateDddArgs } from "./CreateDddArgs";
import { UpdateDddArgs } from "./UpdateDddArgs";
import { DeleteDddArgs } from "./DeleteDddArgs";
import { DddFindManyArgs } from "./DddFindManyArgs";
import { DddFindUniqueArgs } from "./DddFindUniqueArgs";
import { Ddd } from "./Ddd";
import { DddService } from "../ddd.service";
@graphql.Resolver(() => Ddd)
export class DddResolverBase {
  constructor(protected readonly service: DddService) {}

  async _dddsMeta(
    @graphql.Args() args: DddFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Ddd])
  async ddds(@graphql.Args() args: DddFindManyArgs): Promise<Ddd[]> {
    return this.service.findMany(args);
  }

  @graphql.Query(() => Ddd, { nullable: true })
  async ddd(@graphql.Args() args: DddFindUniqueArgs): Promise<Ddd | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Ddd)
  async createDdd(@graphql.Args() args: CreateDddArgs): Promise<Ddd> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Ddd)
  async updateDdd(@graphql.Args() args: UpdateDddArgs): Promise<Ddd | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Ddd)
  async deleteDdd(@graphql.Args() args: DeleteDddArgs): Promise<Ddd | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
